// This file is generated

F_marr_place_1 = [
"Toronto, Ontario, Canada",
"",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Thunder Bay, Ontario, Canada",
"Bretanha, Azores, Portugal",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Espirito Santo.Fall River Mass.",
"Bretanha, Azores, Portugal",
"",
"Bretanha, Azores, Portugal",
"",
"Bretanha, Azores, Portugal",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Bretanha, Azores, Portugal",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"",
"Ermida Nossa Senhora dos Rem\u00e9dios",
"",
"Bretanha, Azores, Portugal",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"S. Ant\u00f3nio al\u00e9m Capelas",
"Faj\u00e3 de Baixo, S\u00e3o Miguel, A\u00e7ores",
"Bretanha, Azores, Portugal",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"",
"S. Ant\u00f3nio al\u00e9m Capelas",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Ajuda, Bretanha, S\u00e3o Miguel, A\u00e7ores",
"Mosteiros, Azores, Portugal",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"S. Jos\u00e9 de Ponta Delgada",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Rem\u00e9dios ,Bretanha",
"Fall River, Bristol, Massachusetts, USA",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Arrifes, Azores, Portugal",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Bretanha, Azores, Portugal",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Bretanha, Azores, Portugal",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Bretanha, Azores, Portugal",
"",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Mosteiros, Azores, Portugal",
"",
"",
"Candel\u00e1ria,S\u00e3o Miguel, A\u00e7ores",
"Mosteiros, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Relva, S\u00e3o Miguel, A\u00e7ores",
"",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Rem\u00e9dios ,Bretanha",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Ajuda, Bretanha, S\u00e3o Miguel, A\u00e7ores",
"Bretanha, Azores, Portugal",
"",
"Rem\u00e9dios ,Bretanha",
"",
"",
"Bretanha, Azores, Portugal",
"",
"",
"",
"Rem\u00e9dios ,Bretanha",
"",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Bretanha, Azores, Portugal",
"Ottawa, Ontario, Canada",
"Bretanha, Azores, Portugal",
"Fenais da Luz, A\u00e7ores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Capelas, Azores, Portugal",
"Bretanha, Azores, Portugal",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"",
"",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"S. Ant\u00f3nio al\u00e9m Capelas",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Ginetes, Azores, Portugal",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"",
"Ginetes, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"Rem\u00e9dios ,Bretanha",
"Ajuda, Bretanha, S\u00e3o Miguel, A\u00e7ores",
"Rem\u00e9dios, Bretanha",
"Bretanha, Azores, Portugal",
"",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Bretanha, Azores, Portugal",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Capelas, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"Bretanha, Azores, Portugal",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Bretanha, Azores, Portugal",
"",
"",
"",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Bretanha, Azores, Portugal",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"Matriz de S\u00e3o Sebasti\u00e3o, Ponta Delgada, S\u00e3o Miguel, A\u00e7ores.",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Rem\u00e9dios ,Bretanha",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"",
"Capelas, Azores, Portugal",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Bretanha, Azores, Portugal",
"Feteiras do Sul, S\u00e3o Miguel, A\u00e7ores",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Maia, S\u00e3o Miguel, A\u00e7ores",
"",
"Bretanha, Azores, Portugal",
"",
"",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Bretanha, Azores, Portugal",
"",
"Rem\u00e9dios ,Bretanha",
"Rem\u00e9dios ,Bretanha",
"Bretanha, Azores, Portugal",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"S\u00e3o Sebasti\u00e3o Ginetes,S\u00e3o Miguel, A\u00e7ores",
"Bretanha, Azores, Portugal",
"Capelas, Azores, Portugal",
"Capelas, Azores, Portugal",
"Ribeira das Tainhas, Azores, Portugal",
"",
"Hamilton, Ontario, Canada",
"",
"",
"Ajuda, Bretanha, S\u00e3o Miguel, A\u00e7ores",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"",
"",
"Matriz de S\u00e3o Jorge, Nordeste, S\u00e3o Miguel, A\u00e7ores",
"",
"",
"",
"",
"",
"",
"",
"Capelas, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"",
"",
"Bretanha, Azores, Portugal",
"",
"Ginetes, Azores, Portugal",
"S. Pedro da Ribeira Grande",
"",
"",
"",
"S. Ant\u00f3nio al\u00e9m Capelas",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"",
"N.S. da Conceicao, Ribeira Grande, Acores",
"",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"",
"",
"",
"",
"",
"",
"Bretanha, Azores, Portugal",
"",
"",
"",
"",
"Bretanha, Azores, Portugal",
"S\u00e3o Pedro da Ribeira Seca, Acores",
"",
"N.S.da Estrella, R.Grande, A\u00e7ores",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"Bretanha, Azores, Portugal",
"Santo Cristo, Fall River Mass",
"",
"Rabo de Peixe, Azores, Portugal",
"",
"",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"S. Ant\u00f3nio al\u00e9m Capelas",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Ginetes, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"",
"",
"Candel\u00e1ria,S\u00e3o Miguel, A\u00e7ores",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Bretanha, Azores, Portugal",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Bretanha, Azores, Portugal",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"",
"",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Rem\u00e9dios ,Bretanha",
"Bretanha, Azores, Portugal",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"",
"",
"",
"",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"S\u00e3o Jos\u00e9,Ponta Delgada ,A\u00e7\u00f4res",
"",
"",
"Bretanha, Azores, Portugal",
"",
"",
"Bretanha, Azores, Portugal",
"S\u00e3o Jos\u00e9,Ponta Delgada ,A\u00e7\u00f4res",
"",
"",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Rabo de Peixe, Azores, Portugal",
"Rabo de Peixe, Azores, Portugal",
"Capelas, Azores, Portugal",
"Capelas, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"Bretanha, Azores, Portugal",
"",
"",
"",
"N.S.da Estrella, R.Grande, A\u00e7ores",
"",
"",
"",
"Ajuda, Bretanha, S\u00e3o Miguel, A\u00e7ores",
"S. Pedro da Ribeira Seca, S\u00e3o Miguel, A\u00e7ores",
"",
"",
"",
"",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Thunder Bay, Ontario, Canada",
"Matriz Ribeira Grande",
"Bretanha, A\u00e7\u00f4res, Portugal",
"",
"Bretanha, Azores, Portugal",
"",
"",
"",
"",
"",
"Ponta Gar\u00e7a, S\u00e3o Miguel, A\u00e7ores",
"Ponta Gar\u00e7a, S\u00e3o Miguel, A\u00e7ores",
"",
"",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"Bretanha, Azores, Portugal",
"",
"",
"Bretanha, Azores, Portugal",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Bretanha, Azores, Portugal",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"",
"Bretanha, Azores, Portugal",
"",
"",
"",
"",
"",
"",
"Bretanha, Azores, Portugal",
"Sainte-C\u00e9cile-de-Masham,Outaouais, Qu\u00e9bec, CANADA",
"St Antoine de Padua, Riviere du Loup, Louiseville, Maskinonge, Quebec",
"Aylmer, Gatineau, Quebec, Canada",
"",
"",
"Sainte-C\u00e9cile-de-Masham,Outaouais, Qu\u00e9bec, CANADA",
"",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"",
"Ajuda, Bretanha, S\u00e3o Miguel, A\u00e7ores",
"Ajuda, Bretanha, S\u00e3o Miguel, A\u00e7ores",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Ajuda, Bretanha, S\u00e3o Miguel, A\u00e7ores",
"Mosteiros, Azores, Portugal",
"",
"",
"Mosteiros, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Ginetes, Azores, Portugal",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Bretanha, Azores, Portugal",
"",
"Bretanha, Azores, Portugal",
"",
"Santa B\u00e1rbara- St\u00ba Ant\u00f3nio-al\u00e9m-Capelas",
"",
"Bretanha, Azores, Portugal",
"S\u00e3o Jos\u00e9,Ponta Delgada ,A\u00e7\u00f4res",
"",
"",
"Rabo de Peixe, Azores, Portugal",
"",
"",
"Bretanha, Azores, Portugal",
"",
"",
"",
"Bretanha, Azores, Portugal",
"S\u00e3o Jos\u00e9,Ponta Delgada ,A\u00e7\u00f4res",
"Capelas, Azores, Portugal",
"",
"",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Bretanha, Azores, Portugal",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"",
"",
"",
"Bretanha, Azores, Portugal",
"",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"",
"",
"",
"",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Bretanha, Azores, Portugal",
"USA",
"",
"Bretanha, Azores, Portugal",
"",
"Bretanha, Azores, Portugal",
"",
"",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"",
"",
"",
"Bretanha, Azores, Portugal",
"Rem\u00e9dios, Bretanha",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Bretanha, Azores, Portugal",
"",
"",
"",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"",
"",
"Capelas, Azores, Portugal",
"S\u00e3o Jos\u00e9,Ponta Delgada ,A\u00e7\u00f4res",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"",
"Rem\u00e9dios ,Bretanha",
"",
"Bretanha, Azores, Portugal",
"",
"Varzea, S\u00e3o Miguel, A\u00e7ores",
"",
"Bretanha, Azores, Portugal",
"",
"Bretanha, Azores, Portugal",
"Ajuda, Bretanha, S\u00e3o Miguel, A\u00e7ores",
"",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"S. Ant\u00f3nio al\u00e9m Capelas",
"",
"Bretanha, Azores, Portugal",
"Capelas, Azores, Portugal",
"",
"Saint-Anicet, Mont\u00e9r\u00e9gie, Qu\u00e9bec, CANADA",
"",
"",
"Bretanha, Azores, Portugal",
"S. Pedro da Ribeira Seca, S\u00e3o Miguel, A\u00e7ores",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Capelas, Azores, Portugal",
"",
"Capelas, Azores, Portugal",
"Capelas, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"Bretanha, Azores, Portugal",
"",
"Bretanha, Azores, Portugal",
"Capelas, Azores, Portugal",
"Fenais da Ajuda, Azores, Portugal",
"",
"Arrifes, Azores, Portugal",
"",
"Feteiras do Sul, S\u00e3o Miguel, A\u00e7ores",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Fall River, Bristol, Massachusetts, USA",
"Relva, S\u00e3o Miguel, A\u00e7ores",
"Fall River, Bristol, Massachusetts, USA",
"Bretanha, Azores, Portugal",
"",
"",
"Rem\u00e9dios ,Bretanha",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Fall River, Bristol, Massachusetts, USA",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"S. Ant\u00f3nio al\u00e9m Capelas",
"",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"",
"",
"S. Ant\u00f3nio al\u00e9m Capelas",
"",
"Matriz Ribeira Grande",
"",
"",
"Madeira, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Fall River, Bristol, Massachusetts, USA",
"",
"Bretanha, Azores, Portugal",
"",
"",
"",
"Bretanha, Azores, Portugal",
"",
"Rem\u00e9dios ,Bretanha",
"Bretanha, Azores, Portugal",
"Ajuda, Bretanha, S\u00e3o Miguel, A\u00e7ores",
"Bretanha, Azores, Portugal",
"",
"",
"",
"Bretanha, Azores, Portugal",
"Fall River, Bristol, Massachusetts, USA",
"Bretanha, Azores, Portugal",
"",
"",
"",
"Ajuda, Bretanha, S\u00e3o Miguel, A\u00e7ores",
"Bretanha, Azores, Portugal",
"",
"Rem\u00e9dios ,Bretanha",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Bretanha, Azores, Portugal",
"Ajuda, Bretanha, S\u00e3o Miguel, A\u00e7ores",
"",
"Rem\u00e9dios, Bretanha",
"",
"Rem\u00e9dios ,Bretanha",
"Rem\u00e9dios ,Bretanha",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"",
"",
"",
"",
"",
"",
"Bretanha, Azores, Portugal",
"",
"Bretanha, Azores, Portugal",
"",
"Cumberland, Rhode Island.",
"Rem\u00e9dios ,Bretanha",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"",
"S. Ant\u00f3nio al\u00e9m Capelas",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Bretanha, Azores, Portugal",
"",
"Ajuda, Bretanha, S\u00e3o Miguel, A\u00e7ores",
"",
"",
"",
"",
"",
"S\u00e3o Miguel,Azores",
"Lomba de Santa Barbara ,Ribeira Grande",
"",
"S. Ant\u00f3nio al\u00e9m Capelas",
"Bretanha, Azores, Portugal",
"",
"",
"Capelas, Azores, Portugal",
"",
"Rabo de Peixe, Azores, Portugal",
"",
"",
"S\u00e3o Pedro Nordestino, A\u00e7ores",
"",
"Mosteiros, Azores, Portugal",
"",
"",
"Bretanha, Azores, Portugal",
"Capelas, Azores, Portugal",
"",
"",
"",
"",
"Ajuda, Bretanha, S\u00e3o Miguel, A\u00e7ores",
"Bretanha, Azores, Portugal",
"",
"",
"",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"",
"",
"",
"",
"S. Ant\u00f3nio al\u00e9m Capelas",
"S. Ant\u00f3nio al\u00e9m Capelas",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"Bretanha, Azores, Portugal",
"Rabo de Peixe, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"Capelas, Azores, Portugal",
"Rabo de Peixe, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Rabo de Peixe, Azores, Portugal",
"S\u00e3o Pedro, Ponta Delgada A\u00e7\u00f4res",
"",
"S\u00e3o Jos\u00e9,Ponta Delgada ,A\u00e7\u00f4res",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Bretanha, Azores, Portugal",
"",
"Rabo de Peixe, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"Rabo de Peixe, Azores, Portugal",
"",
"Rabo de Peixe, Azores, Portugal",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Bretanha, Azores, Portugal",
"Capelas, Azores, Portugal",
"S. Ant\u00f3nio al\u00e9m Capelas",
"S. Ant\u00f3nio al\u00e9m Capelas",
"",
"Bretanha, Azores, Portugal",
"",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Rem\u00e9dios ,Bretanha",
"",
"",
"",
"Ribeira Grande, A\u00e7ores",
"Capelas, Azores, Portugal",
"Ginetes, Azores, Portugal",
"",
"S. Ant\u00f3nio al\u00e9m Capelas",
"",
"",
"Bretanha, Azores, Portugal",
"",
"",
"",
"",
"S. Ant\u00f3nio al\u00e9m Capelas",
"Bretanha, Azores, Portugal",
"Capelas, Azores, Portugal",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Bretanha, Azores, Portugal",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"",
"",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"",
"Bretanha, Azores, Portugal",
"",
"Faj\u00e3 de Cima, Azores, Portugal",
"Ajuda, Bretanha, S\u00e3o Miguel, A\u00e7ores",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Ginetes, Azores, Portugal",
"Candel\u00e1ria,S\u00e3o Miguel, A\u00e7ores",
"",
"",
"Rem\u00e9dios ,Bretanha",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"S. Pedro da Ribeira Seca, S\u00e3o Miguel, A\u00e7ores",
"S. Ant\u00f3nio al\u00e9m Capelas",
"Ginetes, Azores, Portugal",
"Fenais da Luz, A\u00e7ores, Portugal",
"",
"Bretanha, Azores, Portugal",
"",
"Relva, S\u00e3o Miguel, A\u00e7ores",
"",
"",
"Rabo de Peixe, Azores, Portugal",
"",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"S. Ant\u00f3nio al\u00e9m Capelas",
"",
"",
"",
"",
"",
"",
"",
"",
"Bretanha, Azores, Portugal",
"",
"Rabo de Peixe, Azores, Portugal",
"",
"",
"St\u00ba. Esp\u00edrito, ilha de Santa Maria",
"Bretanha, Azores, Portugal",
"",
"",
"",
"",
"",
"Bretanha, Azores, Portugal",
"S. Ant\u00f3nio al\u00e9m Capelas",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"",
"",
"",
"",
"",
"N.S. da Conceicao, Ribeira Grande, Acores",
"S\u00e3o Pedro da Ribeira Seca, Acores",
"",
"",
"",
"",
"Rabo de Peixe, Azores, Portugal",
"Fenais da Luz, A\u00e7ores, Portugal",
"",
"Rabo de Peixe, Azores, Portugal",
"",
"Bretanha, Azores, Portugal",
"",
"",
"Rabo de Peixe, Azores, Portugal",
"Feteiras do Sul, S\u00e3o Miguel, A\u00e7ores",
"",
"",
"S. Ant\u00f3nio al\u00e9m Capelas",
"",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"",
"S\u00e3o Sebasti\u00e3o Ginetes,S\u00e3o Miguel, A\u00e7ores",
"",
"",
"Hamilton, Ontario, Canada",
"Bretanha, Azores, Portugal",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Bretanha, Azores, Portugal",
"",
"",
"Bretanha, Azores, Portugal",
"Fall River, Bristol, Massachusetts, USA",
"",
"",
"",
"",
"Ginetes, Azores, Portugal",
"Hamilton, Ontario, Canada",
"",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Hamilton, Ontario, Canada",
"Bretanha, Azores, Portugal",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"",
"",
"S\u00e3o Sebasti\u00e3o Ginetes,S\u00e3o Miguel, A\u00e7ores",
"Mosteiros, Azores, Portugal",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"Bretanha, Azores, Portugal",
"Rem\u00e9dios ,Bretanha",
"Bretanha, Azores, Portugal",
"Santa B\u00e1rbara- St\u00ba Ant\u00f3nio-al\u00e9m-Capelas",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Rem\u00e9dios ,Bretanha",
"Bretanha, Azores, Portugal",
"St\u00aa Barbara-al\u00e9m- Capelas",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"Fall River, Bristol, Massachusetts, USA",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"",
"N\u00aa S\u00aa da Ajuda Bretanha,S\u00e3o Miguel,A\u00e7ores",
"S. Ant\u00f3nio al\u00e9m Capelas",
"Bretanha, Azores, Portugal",
"",
"Bretanha, Azores, Portugal",
"Ajuda, Bretanha, S\u00e3o Miguel, A\u00e7ores",
"Bretanha, Azores, Portugal",
"",
"",
"",
"S. Ant\u00f3nio al\u00e9m Capelas",
"Bretanha, Azores, Portugal",
"Pilar Bretanha, S\u00e3o Miguel A\u00e7ores",
"",
"",
"Bretanha, Azores, Portugal",
"",
"",
"",
"",
"",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"Bretanha, Azores, Portugal",
"",
"",
"Ginetes, Azores, Portugal",
"",
"",
"",
"Bretanha, Azores, Portugal",
""
]
Dwr.ScriptLoaded('dwr_db_F_marr_place_1.js');
