// This file is generated

F_name_1 = [
"Family of Raposo, Jos\u00e9 Maria Viveiros and Brasil, Maria do Carmo Oliveira",
"Family of Raposo, Jos\u00e9 Maur\u00edcio and De Jesus, Francisca",
"Family of Raposo, Jos\u00e9 Novo and Medeiros, Mariana da Costa",
"Family of Raposo, Jos\u00e9 Paulo and Pacheco, Nat\u00e1lia",
"Family of Raposo, Jos\u00e9 Pimentel and Isabel, Francisca",
"Family of Raposo, Jos\u00e9 Pimentel and Medeiros, Eduarda M\u00aa Fernandes",
"Family of Raposo, Jos\u00e9 Rodrigues and Couto, Maria do",
"Family of Raposo, Jos\u00e9 Rodrigues and de Jesus, Francisca",
"Family of Raposo, Laudalino Jos\u00e9 Pimentel and Viveiros, Judite Maria Miguel",
"Family of Raposo, Luis and da Estrela, Maria",
"Family of Raposo, Lu\u00eds and Novo, Maria da Luz",
"Family of Raposo, Luis Francisco and Angelina, Maria",
"Family of Raposo, Lu\u00eds Francisco and Aguiar, Maria Juliana",
"Family of Raposo, Lu\u00eds Francisco and da Conceic\u00e3o, Maria",
"Family of Raposo, Lu\u00eds Francisco and de Viveiros, Cec\u00edlia",
"Family of Raposo, Luis Isid\u00f3rio and Augusta, Margarida",
"Family of Raposo, Luis Isid\u00f3rio and da Conceic\u00e3o, Joana",
"Family of Raposo, Luis Jacinto and da Concei\u00e7\u00e3o, Maria Tomasia",
"Family of Raposo, Manuel and Albernaz, Maria Jacinta",
"Family of Raposo, Manuel and Calvo, Joaquina",
"Family of Raposo, Manuel and Cordeiro, Maria de Jesus",
"Family of Raposo, Manuel and Correia, Eul\u00e1lia Medeiros",
"Family of Raposo, Manuel and de Aguiar, Maria",
"Family of Raposo, Manuel and de Jesus, Maria",
"Family of Raposo, Manuel and de Medeiros, Ana",
"Family of Raposo, Manuel and de Sousa, Esperan\u00e7a",
"Family of Raposo, Manuel and Gon\u00e7alves, Ana",
"Family of Raposo, Manuel and Grota, Ana Medeiros",
"Family of Raposo, Manuel and Joaquina, Ana",
"Family of Raposo, Manuel and Medeiros, Maria Da Concei\u00e7\u00e3o",
"Family of Raposo, Manuel and Miguel, Ant\u00f3nia de S\u00e3o",
"Family of Raposo, Manuel and Pereira, Maria Irene dos Anjos",
"Family of Raposo, Manuel and Raposo, Maria Emilia",
"Family of Raposo, Manuel and Viveiros, Encarna\u00e7\u00e3o Pereira",
"Family of Raposo, Manuel * and da Costa, Ana *",
"Family of Raposo, Manuel Alves and da Conceic\u00e3o, Maria",
"Family of Raposo, Manuel \u00c1lves and Cabral, Maria da Gl\u00f3ria",
"Family of Raposo, Manuel \u00c1lves and dos Anjos, Joaquina",
"Family of Raposo, Manuel \u00c1lves and Ermelinda, Francisca",
"Family of Raposo, Manuel \u00c1lves and Leonor, Maria",
"Family of Raposo, Manuel \u00c1lves and Viveiros, Maria da Conceic\u00e3o",
"Family of Raposo, Manuel Correia and Martins, Silvana Pimentel",
"Family of Raposo, Manuel Dias and da Estrela, Maria",
"Family of Raposo, Manuel Domingos Sousa and Fernandes, Maria Helena",
"Family of Raposo, Manuel Duarte and de Faria, Mariana Raposo",
"Family of Raposo, Manuel Duarte and de Sousa, Maria",
"Family of Raposo, Manuel Duarte and dos Anjos, Maria",
"Family of Raposo, Manuel Ferreira and Augusta, Maria",
"Family of Raposo, Manuel Francisco and Cabral, Florinda",
"Family of Raposo, Manuel Francisco and Costa, Maria J\u00falia",
"Family of Raposo, Manuel Francisco and Farias, Filomena Bernardo",
"Family of Raposo, Manuel Francisco and Luciano, Deolinda",
"Family of Raposo, Manuel Francisco and Santo, Tomasia do Espirito",
"Family of Raposo, Manuel Isid\u00f3rio and Tavares, Maria Jos\u00e9",
"Family of Raposo, Manuel Jacinto and de Jesus, Em\u00edlia",
"Family of Raposo, Manuel Jos\u00e9 and de Jesus, Delfina",
"Family of Raposo, Manuel Luis and Manica, Mariana Viveiros",
"Family of Raposo, Manuel Luis and Moniz, Maria Margarida",
"Family of Raposo, Manuel Pimentel and da Conceic\u00e3o, Maria",
"Family of Raposo, Manuel Pimentel and da Concei\u00e7\u00e3o, Mariana Carolina",
"Family of Raposo, Manuel Pimentel and de Oliveira, Maria Segunda",
"Family of Raposo, Manuel Pimentel and Rodrigues, Maria das Mec\u00eas",
"Family of Raposo, Manuel Pimentel and Santo, Maria do Espirito",
"Family of Raposo, Manuel Viveiros and Moreira, Ana Maria Medeiros",
"Family of Raposo, Maria Duarte",
"Family of Raposo, Maria Venilde Medeiros and Raposo, Jorge Sousa",
"Family of Raposo, Matias and dos Reis, Maria",
"Family of Raposo, Miguel and Aguiar, Maria",
"Family of Raposo, Pedro and Furtado, Fatima Raposo",
"Family of Raposo, Pedro and Rodrigues, Maria",
"Family of Raposo, Sebasti\u00e3o and Cabral, Ant\u00f3nia",
"Family of Raposo, Sim\u00e3o Pacheco and Vasconcelos, Barbara Ara\u00fajo",
"Family of Raposo, Tom\u00e1s and Jacinta, Ana",
"Family of Raposo, Tom\u00e9 and Jacinta, Ana",
"Family of Raposo, Vicente and Soares, Ant\u00f3nia",
"Family of Raposo Camelo, Jo\u00e3o and de Jesus, Lucinda",
"Family of Raposo Furtado, Ant\u00f3nio and da Concei\u00e7\u00e3o, Ana",
"Family of Raposo Furtado, Ant\u00f3nio and Da Gloria, Maria",
"Family of Raposo Furtado, Ant\u00f3nio and Lima, Rosa Da Costa",
"Family of Raposo Furtado, Ant\u00f3nio and Pav\u00e3o, Maria Natalia Faria",
"Family of Raposo Furtado, Ant\u00f3nio and Tavares, Maria Jesus",
"Family of Raposo Furtado, Augusto and Arruda, Maria do Carmo",
"Family of Raposo Furtado, Jacinto and Almeida, Mariana J\u00falia",
"Family of Raposo Furtado, Jacinto and Couto, Mariana Martins do",
"Family of Raposo Furtado, Jo\u00e3o and Carvalho, Od\u00edlia",
"Family of Raposo Furtado, Jo\u00e3o and de Jesus, Margarida",
"Family of Raposo Furtado, Jo\u00e3o and Gon\u00e7alo, Ana de Jesus",
"Family of Raposo Furtado, Jo\u00e3o and Lindo, Maria Emilia da Concei\u00e7\u00e3o",
"Family of Raposo Furtado, Jo\u00e3o and Medeiros, Ermelina Bento",
"Family of Raposo Furtado, Joaquim and De Sousa, Rosa",
"Family of Raposo Furtado, Manuel and Rego, Maria da Luz",
"Family of Raposo Furtado, Manuel Junior and Alexandre, Maria de Jesus",
"Family of Rasteiro, Ant\u00f3nio de Medeiros and da Luz, Maria",
"Family of Rasteiro, Francisco de Medeiros and Teresa, Maria",
"Family of Rebelo, Ant\u00f3nio and de Almeida, Margarida",
"Family of Rebelo, Ant\u00f3nio Aguiar and Furtado, Maria Miguel",
"Family of Rebelo, Ant\u00f3nio de Sousa and Andrade, Mariana Branco",
"Family of Rebelo, David and de Oliveira, Mariana",
"Family of Rebelo, Domingos and dos Reis, Margarida Pacheco",
"Family of Rebelo, Jacinto and De Jesus, Maria",
"Family of Rebelo, Jenna",
"Family of Rebelo, Joe and Furtado, Od\u00e1lia",
"Family of Rebelo, Jos\u00e9 Reis and Arruda, Lub\u00e9lia da Luz Vicente",
"Family of Rebelo, Jos\u00e9 Aguiar and Rodrigues, Maria",
"Family of Rebelo, Manuel Aguiar and de Sousa, Maria Rosa",
"Family of Rego, Agostinho do and Borges, Alexandrinha",
"Family of Rego, Am\u00e9rico and Rego, Donualda do",
"Family of Rego, Ant\u00f3nio and Sousa, Maria Angelina",
"Family of Rego, Ant\u00f3nio Dias do and Francisco, Maria",
"Family of Rego, Ant\u00f3nio do and Almeida, Em\u00edlia",
"Family of Rego, Ant\u00f3nio do and Arruda, Mariana",
"Family of Rego, Ant\u00f3nio do and Castanho, Maria",
"Family of Rego, Ant\u00f3nio do and da Concei\u00e7\u00e3o, Madalena",
"Family of Rego, Ant\u00f3nio do and da Conceic\u00e3o, Mariana",
"Family of Rego, Ant\u00f3nio do and de Benevides, Esperan\u00e7a",
"Family of Rego, Ant\u00f3nio do and de Faria, Maria Ign\u00e1cia",
"Family of Rego, Ant\u00f3nio do and de Oliveira, Maria",
"Family of Rego, Ant\u00f3nio do and Vasconcelos, Ana Costa",
"Family of Rego, Artur Pav\u00e3o do and Pav\u00e3o, Maria da Conceic\u00e3o",
"Family of Rego, Caetano do and de Jesus, Ana Clemantina",
"Family of Rego, Caetano do and Soares, Maria",
"Family of Rego, Clara do",
"Family of Rego, Darcio and Rego, Maria do",
"Family of Rego, Domingos do and de Jesus, Maria",
"Family of Rego, Edmundo and Ros\u00e1rio, Maria do",
"Family of Rego, Francisco de Viveiros and de Medeiros, Joana Maria",
"Family of Rego, Francisco do and Benevides, Isabel de",
"Family of Rego, Francisco do and Carvalho, Umblina de Jesus",
"Family of Rego, Francisco do and da Conceic\u00e3o, Maria",
"Family of Rego, Francisco do and De Medeiros, Maria",
"Family of Rego, Francisco do and de Oliveira, Mariana",
"Family of Rego, Francisco do and de Sousa, Guiomar",
"Family of Rego, Francisco do and de Sousa, Jos\u00e9fa",
"Family of Rego, Francisco do and Pav\u00e3o, Senhorinha Rosa do Carmo",
"Family of Rego, Francisco do and Pereira, Sara Peres",
"Family of Rego, Francisco do and Teves, Maria De",
"Family of Rego, Francisco do and Viveiros, Maria da Concei\u00e7\u00e3o",
"Family of Rego, Humberto do and Rego, Virginia do",
"Family of Rego, Jacinto and dos Anjos, Em\u00edlia",
"Family of Rego, Jacinto Caetano and Joaquina, Maria",
"Family of Rego, Jacinto do and Albernaz, Maria dos Santos",
"Family of Rego, Jacinto do and Moreira, Maria da Luz",
"Family of Rego, Jo\u00e3o de Oliveira and de Benevides, Ana Bernarda Maria",
"Family of Rego, Jo\u00e3o do and Alexandre, Maria de Lurdes",
"Family of Rego, Jo\u00e3o do and da Conceic\u00e3o, Maria",
"Family of Rego, Jo\u00e3o do and da Concei\u00e7\u00e3o, Maria",
"Family of Rego, Jo\u00e3o do and de Jesus, Maria",
"Family of Rego, Jo\u00e3o do and de Viveiros, Esperan\u00e7a",
"Family of Rego, Jo\u00e3o do and Fernandes, Catarina",
"Family of Rego, Jo\u00e3o do and Pedro, Mariana",
"Family of Rego, Jo\u00e3o do and Rodrigues, Ana Leite",
"Family of Rego, Jo\u00e3o Jos\u00e9 do and Machado, Francisca Dos Anjos",
"Family of Rego, Jo\u00e3o Luis do",
"Family of Rego, Jo\u00e3o Mariano do and de Jesus, Ana",
"Family of Rego, Jo\u00e3o Medeiros and , Margarida",
"Family of Rego, Jos\u00e9 Deodato do and Miranda, Luc\u00edlia Raposo",
"Family of Rego, Jos\u00e9 do and Arruda, Maria",
"Family of Rego, Jos\u00e9 do and Cordeiro, Maria do Carmo",
"Family of Rego, Jos\u00e9 do and de Jesus, Carolina",
"Family of Rego, Jos\u00e9 do and de Oliveira, Maria",
"Family of Rego, Jos\u00e9 do and Fortin, Linda",
"Family of Rego, Jos\u00e9 do and Franco, Luzia de Jesus",
"Family of Rego, Jos\u00e9 do and Matias, Maria de S\u00e3o",
"Family of Rego, Jos\u00e9 do and Rodrigues, Ana da Concei\u00e7\u00e3o",
"Family of Rego, Jos\u00e9 do and Teves, Ant\u00f3nia de Jesus",
"Family of Rego, Jos\u00e9 do and Travassos, Maria da Estrela",
"Family of Rego, Jos\u00e9 Jacinto do and Aguiar, Belmira",
"Family of Rego, Jos\u00e9 Mariano do and da Conceic\u00e3o, Maria",
"Family of Rego, Lino and Rego, Janet",
"Family of Rego, Luis do and da Estrela, Ant\u00f3nia",
"Family of Rego, Luis do and Faria, Margarida da Trindade",
"Family of Rego, Luis do and Tavares, Lu\u00edsa",
"Family of Rego, Manuel and da Encarna\u00e7\u00e3o, Jos\u00e9fa",
"Family of Rego, Manuel and Medeiros, Mariana dos Anjos",
"Family of Rego, Manuel Caetano do and de Jesus, Clemantina",
"Family of Rego, Manuel Caetano do and Raposo, Maria",
"Family of Rego, Manuel de Sousa and Furtada, Ant\u00f3nia",
"Family of Rego, Manuel do and da Conceic\u00e3o, Mariana",
"Family of Rego, Manuel do and da Luz, Fernanda Miguel",
"Family of Rego, Manuel do and Dinis, Maria",
"Family of Rego, Manuel do and dos Anjos, Maria",
"Family of Rego, Manuel do and Melo, Maria dos Anjos",
"Family of Rego, Manuel do and Pacheco, Maria de Sousa",
"Family of Rego, Manuel do and Paiva, Quiteria de Jesus",
"Family of Rego, Manuel do and Paulina, Rosa",
"Family of Rego, Manuel do and Tavares, Laurina Arruda",
"Family of Rego, Manuel Jacinto and Soares, Venilde Maria",
"Family of Rego, Manuel Pav\u00e3o do and Arruda, Leonor Augusta da Concei\u00e7\u00e3o",
"Family of Rego, Manuel Pav\u00e3o do and da Ponte, Sofia",
"Family of Rego, Maria Joaquina do and de Ara\u00fajo, Francisco",
"Family of Rego, Matias do and Carvalha, Vit\u00f3ria de Jesus",
"Family of Rego, Messias Oliveira and Oliveira, Maria Leonor",
"Family of Rego, Pedro do and da Cruz, Monica",
"Family of Rego, Pedro Viveiros do and de Oliveira, Maria Rodrigues",
"Family of Rego, Tom\u00e1s de Sousa and De Macedo, Gertrudes",
"Family of Rego, Tom\u00e9 do and Soares, Maria",
"Family of Rei, Jo\u00e3o de Medeiros and da Concei\u00e7\u00e3o, Maria J\u00falia",
"Family of Rei, Jos\u00e9 de Medeiros and de Jesus, Fortunata",
"Family of Reid, James and Guerreiro, Megan Ann",
"Family of Reis, Agostinho de Sousa and Reis, Maria da Concei\u00e7\u00e3o",
"Family of Reis, Ant\u00f3nio da Costa and Resendes, Isaura",
"Family of Reis, Dinis and da Silva, Margarida",
"Family of Reis, Jos\u00e9 Manuel Oliveira and Espinola, Maria do Ros\u00e1rio Cordeiro",
"Family of Reis, Maria do Ros\u00e1rio and dos Reis, Agostinho Maria",
"Family of Reis, Rui and Reis, Gilda",
"Family of Resendes, Agostinho De and Viveiros, Br\u00edgida De",
"Family of Resendes, Francisco Pimentel and Furtado, Rufina",
"Family of Resendes, Manuel da Costa and Tavares, Maria",
"Family of Resendes, Roque Afonso Pimentel and Coelho, Eva",
"Family of Revoredo, Bartolomeu and Dias, Catarina",
"Family of Ribeiro, Manuel Teixeira and Teixeira, Maria C\u00e2ndida",
"Family of Ribeiro, Rodrigo Afonso and Godins, Urraca",
"Family of Robison, N and Arruda, Susete",
"Family of Rocha, Ant\u00f3nio \u00c1lves and de Benevides, Maria",
"Family of Rocha, Ant\u00f3nio de Paiva and de Viveiros, Ana",
"Family of Rocha, Cosme da and de Figueiredo, Leonor",
"Family of Rocha, Cosme da and Medeiros, Luzia de",
"Family of Rocha, Em\u00edlia de Jesus \u00c1lvares",
"Family of Rocha, Jo\u00e3o Maria and Pereira, Maria da Concei\u00e7\u00e3o",
"Family of Rocha, Jos\u00e9 Ant\u00f3nio and Joaquina, Maria",
"Family of Rocha, Jos\u00e9 Mariano and Tom\u00e1sia, Maria",
"Family of Rocha, Manuel and Medeiros, \u00c1gueda",
"Family of Rocha, Manuel de Paiva and Couto, Natalia do",
"Family of Rocha, Manuel De Sousa and Martins, Apol\u00f3nia",
"Family of Rodovalho, Gaspar Correia Tabeli\u00e3o and Cansada, In\u00eas",
"Family of Rodovalho, Manuel da Costa and Manuel, Catarina",
"Family of Rodovalho, Vital da Costa and Soares, Maria",
"Family of Rodrigo, Francisco and de Jesus, Maria",
"Family of Rodrigues, Agostinho Pedro and Pacheco, Maria Jos\u00e9 Carvalho",
"Family of Rodrigues, Alvaro and Rodrigues, Branca",
"Family of Rodrigues, \u00c1lvaro and Carneira, Ana",
"Family of Rodrigues, Andre and Luiz, Catarina",
"Family of Rodrigues, Andr\u00e9 and da Costa, Barbara",
"Family of Rodrigues, An\u00edbal and Arruda, Maria Deolinda",
"Family of Rodrigues, An\u00edbal and Tavares, Maria de Melo",
"Family of Rodrigues, Ant\u00f3nio",
"Family of Rodrigues, Ant\u00f3nio and Cabral, Maria",
"Family of Rodrigues, Ant\u00f3nio and da Costa, Maria",
"Family of Rodrigues, Ant\u00f3nio and de Benevides, B\u00e1rbara",
"Family of Rodrigues, Ant\u00f3nio and de Jesus, Ana",
"Family of Rodrigues, Ant\u00f3nio and de Jesus, Maria",
"Family of Rodrigues, Ant\u00f3nio and De Jesus, Maria Carvalho",
"Family of Rodrigues, Ant\u00f3nio and Fernandes, Isabel",
"Family of Rodrigues, Ant\u00f3nio and Ferreira, Maria",
"Family of Rodrigues, Ant\u00f3nio and Joaquina, Maria",
"Family of Rodrigues, Ant\u00f3nio and Medeiros, Ant\u00f3nia De",
"Family of Rodrigues, Ant\u00f3nio and Nascimento, Ant\u00f3nia do",
"Family of Rodrigues, Ant\u00f3nio and Rodovalho, Francisca Correia",
"Family of Rodrigues, Ant\u00f3nio and Rodrigues, Brizida Agueda",
"Family of Rodrigues, Ant\u00f3nio and Rodrigues, Catarina",
"Family of Rodrigues, Ant\u00f3nio Jos\u00e9 and Ricarda, \u00c1gueda",
"Family of Rodrigues, Ant\u00f3nio Medeiros and Oliveira, Maria Cristina",
"Family of Rodrigues, Ant\u00f3nio Pav\u00e3o",
"Family of Rodrigues, Ant\u00f3nio Pav\u00e3o and Cordeiro, Maria Maur\u00edcio",
"Family of Rodrigues, Ant\u00f3nio Pav\u00e3o and da Gl\u00f3ria, Maria",
"Family of Rodrigues, Bartolomeu and Afonso, Beatriz",
"Family of Rodrigues, Bartolomeu Gon\u00e7alves and de Sousa, Barbara",
"Family of Rodrigues, Danny Coelho and Raposo, Eliane Marie",
"Family of Rodrigues, Domingos and Dias, Maria",
"Family of Rodrigues, Francisco and Arruda, Maria do Carmo",
"Family of Rodrigues, Francisco and Cabeceiras, Ana",
"Family of Rodrigues, Francisco and Calvo, Ant\u00f3nia Joaquina",
"Family of Rodrigues, Francisco and de Jesus, Teresa",
"Family of Rodrigues, Francisco and Oliveira, Ana Joaquina",
"Family of Rodrigues, Francisco and Vultoa, Maria",
"Family of Rodrigues, Francisco In\u00e1cio and De Jesus, Albina",
"Family of Rodrigues, Gon\u00e7alo and Teves, Cecilia",
"Family of Rodrigues, Guilherme and da Conceic\u00e3o, Helena",
"Family of Rodrigues, In\u00e1cio and Francisca, Ant\u00f3nia",
"Family of Rodrigues, In\u00e1cio Jos\u00e9 and Ricarda, Ana",
"Family of Rodrigues, Jo\u00e3o and Carneira, Isabel",
"Family of Rodrigues, Jo\u00e3o and de Aguiar, Ana",
"Family of Rodrigues, Jo\u00e3o and De Aguiar, Maria",
"Family of Rodrigues, Jo\u00e3o and Travassos, B\u00e1rbara",
"Family of Rodrigues, Jo\u00e3o Pedro and da Conceic\u00e3o, Maria",
"Family of Rodrigues, Jo\u00e3o Pedro and dos Anjos, Maria",
"Family of Rodrigues, Jo\u00e3o Pedro and Martins, Maria Eduarda Tavares",
"Family of Rodrigues, Joaquim and de Jesus, Mariana",
"Family of Rodrigues, Jos\u00e9 and Arruda, Mariana das Merc\u00eas",
"Family of Rodrigues, Jos\u00e9 and da Conceic\u00e3o, Maria",
"Family of Rodrigues, Jos\u00e9 and de Jesus, Margarida",
"Family of Rodrigues, Jos\u00e9 and de Jesus, Maria",
"Family of Rodrigues, Jos\u00e9 and de Jesus, Mariana",
"Family of Rodrigues, Jos\u00e9 and de Jesus, Sebastiana",
"Family of Rodrigues, Jos\u00e9 and Diogo, Rosa de Jesus",
"Family of Rodrigues, Jos\u00e9 and J\u00falia, Maria",
"Family of Rodrigues, Jos\u00e9 Soares and Pacheco, Jordelina Moreira",
"Family of Rodrigues, Jos\u00e9 Ant\u00f3nio and C\u00e2ndida, Jacinta",
"Family of Rodrigues, Jos\u00e9 Ant\u00f3nio and Joaquina, Ana",
"Family of Rodrigues, Jos\u00e9 Botelho and de Jesus, Margarida",
"Family of Rodrigues, Jos\u00e9 In\u00e1cio and Constantina, Leonor",
"Family of Rodrigues, Jos\u00e9 In\u00e1cio and Joaquina, Helena",
"Family of Rodrigues, Jos\u00e9 In\u00e1cio Junior and da Concei\u00e7\u00e3o, Ana",
"Family of Rodrigues, Jos\u00e9 Leite and Pacheco, Maria da Gl\u00f3ria",
"Family of Rodrigues, Jos\u00e9 Pedro and Pav\u00e3o, Mariana dos Anjos",
"Family of Rodrigues, Manuel and Aguiar, Maria",
"Family of Rodrigues, Manuel and Carreiro, B\u00e1rbara",
"Family of Rodrigues, Manuel and Carvalha, B\u00e1rbara",
"Family of Rodrigues, Manuel and Carvalho, Mariana",
"Family of Rodrigues, Manuel and da Costa, Maria",
"Family of Rodrigues, Manuel and de Jesus, Joaquina",
"Family of Rodrigues, Manuel and de Jesus, Maria",
"Family of Rodrigues, Manuel and de Medeiros, Maria",
"Family of Rodrigues, Manuel and de Sousa, Barbara",
"Family of Rodrigues, Manuel and de Teves, Luzia",
"Family of Rodrigues, Manuel and Emilia, Ana",
"Family of Rodrigues, Manuel and Ferreira, B\u00e1rbara",
"Family of Rodrigues, Manuel and Jacinta, Rosa",
"Family of Rodrigues, Manuel and Maria, Rosa",
"Family of Rodrigues, Manuel and Nascimento, Mariana do",
"Family of Rodrigues, Manuel and Santo, Ana do Esp\u00edrito",
"Family of Rodrigues, Manuel and Vasconcelos, Ant\u00f3nia",
"Family of Rodrigues, Manuel Pav\u00e3o and da Concei\u00e7\u00e3o, Maria Angelina",
"Family of Rodrigues, Manuel \u00c1lvares * and da Fonseca, Luzia",
"Family of Rodrigues, Manuel \u00c1lvares * and Gon\u00e7alves, Maria",
"Family of Rodrigues, Manuel da Costa and de Macedo, Maria",
"Family of Rodrigues, Manuel da Costa and de Oliveira, Catrina",
"Family of Rodrigues, Manuel de Medeiros and Medeiros, Helena dos Anjos",
"Family of Rodrigues, Manuel de Sousa and Botelho, Maria",
"Family of Rodrigues, Manuel In\u00e1cio and de Jesus, Helena",
"Family of Rodrigues, Manuel Pav\u00e3o and Pav\u00e3o, Maria Jos\u00e9",
"Family of Rodrigues, Manuel Pedro and Dias, Maria Filomena",
"Family of Rodrigues, Mateus and da Costa, Teresa",
"Family of Rodrigues, Melchior and Rodrigues, Ana",
"Family of Rodrigues, Miguel and Cabral, Barbara",
"Family of Rodrigues, Miguel and da Costa, B\u00e1rbara",
"Family of Rodrigues, Pedro and Furtado, Beatriz Fernandes",
"Family of Rodrigues, Pedro and Melo, Ant\u00f3nia Francisca de",
"Family of Rodrigues, Pedro and Rodrigues, Jer\u00f3nima",
"Family of Rodrigues, Ricardo Jos\u00e9 and Carmo, Maria Pedro do",
"Family of Rodrigues, Sebasti\u00e3o and Carvalha, Maria",
"Family of Rodrigues, Tom\u00e9 and Ferreira, Beatriz",
"Family of Roque, Manuel and Francisca, Maria",
"Family of Rosa, Francisca and De Viveiros, Sofia",
"Family of Rosa, Henrique Raposo and Gra\u00e7a, Maria Celisa",
"Family of Rosa, Jos\u00e9 Bento da Costa and Rita, Teresa",
"Family of Ros\u00e1rio, Francisco de Oliveira and de Faria, Alexandrina",
"Family of Ros\u00e1rio, Jo\u00e3o and Carvalho, Maria Francisca",
"Family of Ros\u00e1rio, Jo\u00e3o de Oliveira and Ricarda, Lu\u00edsa",
"Family of Ros\u00e1rio, Jo\u00e3o de Oliveira and Ricarda, Lu\u00edsa",
"Family of Ros\u00e1rio, Maria do",
"Family of S\u00e1, Francisco De Betencour E and Betencourt, Beatriz De S\u00e1",
"Family of S\u00e1, Jo\u00e3o de Betencour E and De Sampaio, Guiomar",
"Family of S\u00e1, Sim\u00e3o De Betencourt E and Gago, Margarida",
"Family of Salgado, Andr\u00e9 Furtado and de Medeiros, Vit\u00f3ria",
"Family of Salgado, Ant\u00f3nio Furtado and Ros\u00e1rio, Maria do",
"Family of Salgado, Pedro Furtado and Moniz, Teresa",
"Family of Salgeiro, Ana de Jesus",
"Family of Salgeiro, Francisco Botelho and Carvalho, Francisca",
"Family of Salgueiro, Andr\u00e9 de Sousa and de Viveiros, Maria",
"Family of Salgueiro, Ant\u00f3nio de Sousa and da Estrela, Maria",
"Family of Salgueiro, Ant\u00f3nio de Sousa and Xavier, Maria",
"Family of Salgueiro, Jos\u00e9 Botelho and dos Reis, Ana",
"Family of Salgueiro, Jos\u00e9 Botelho and dos Santos, Caetana",
"Family of Salgueiro, Jos\u00e9 de Sousa and Jos\u00e9, Ant\u00f3nia de S\u00e3o",
"Family of Salgueiro, Manuel De Melo and Braga, Maria De Jesus",
"Family of Salgueiro, Manuel de Sousa and Araujo, Francisca",
"Family of Salgueiro, Manuel de Sousa and da Ressurrei\u00e7\u00e3o, Ana",
"Family of Salvador, Jos\u00e9 de Sousa and Alexandre, Vit\u00f3ria da Conceic\u00e3o",
"Family of Salvador, Jos\u00e9 de Sousa and C\u00e2ndida, Vit\u00f3ria",
"Family of Salvador, Jos\u00e9 de Sousa and dos Anjos, Maria",
"Family of Salvador, Jos\u00e9 de Sousa Jr and Fernandes, Gilda Rem\u00edgio",
"Family of Salvador, Justino de Sousa and Carvalho, Maria do Carmo",
"Family of Salvador, Justino de Sousa and da Concei\u00e7\u00e3o, Maria J\u00falia",
"Family of Salvador, Justino de Sousa and dos Reis, Senhorinha Fernandes",
"Family of Salvador, Justino de Sousa and Mateus, Maria",
"Family of Salvador, Lu\u00eds de Sousa and dos Anjos, Maria",
"Family of Salvador, Manuel de Sousa and Arruda, Cec\u00edlia",
"Family of Salvador, Manuel de Sousa and Costa, Angela",
"Family of Sandy",
"Family of Santos, Manuel do and De Oliveira, Jos\u00e9fa",
"Family of Santos, Manuel do and Sousa, Quiteria De",
"Family of S\u00e3o-Bento, Jos\u00e9 Raposo and De Jesus, Ana",
"Family of S\u00e3o-Bento, Jos\u00e9 Raposo and Raposo, Leonor \u00c1lves",
"Family of Saucier, Anicet and Goyer-Belisle, Ang\u00e9le Adele",
"Family of Saucier, Fran\u00e7ois R\u00e9gis and Dancosse, Marie Anne",
"Family of Saucier, Joseph Theophile Abraham and Seguin, Marie Alma",
"Family of Sebasti\u00e3o, Ant\u00f3nio de Sousa and da C\u00e2mara, Silvana",
"Family of Sebasti\u00e3o, Manuel and Delfina, Maria",
"Family of Seguin, Edmond and Diotte, Eliza",
"Family of Seguin, Jean -Baptiste and Quesnel, Brigitte Zoe",
"Family of Senra, Angelo da Costa and da Gl\u00f3ria, Mariana",
"Family of Senra, Ant\u00f3nio \u00c1ves and de Benevides, Ana",
"Family of Senra, Ant\u00f3nio da Costa and de Medeiros, Joana",
"Family of Senra, Ant\u00f3nio da Costa and de Melo, Ant\u00f3nia",
"Family of Senra, Ant\u00f3nio de and Furtado, Maria da Estrela",
"Family of Senra, Jo\u00e3o Manuel Oliveira and Pav\u00e3o, Maria de Fatima",
"Family of Senra, Jo\u00e3o Miguel and Pereira, Maria da Encarna\u00e7\u00e3o",
"Family of Senra, Jo\u00e3o Miguel da Costa and da Encarna\u00e7\u00e3o, Maria",
"Family of Senra, Jo\u00e3o Miguel da Costa and Tavares, Senhorinha Isabel",
"Family of Senra, Jos\u00e9 da Costa and Botelho, Vit\u00f3ria",
"Family of Senra, Lu\u00eds da Costa and de Jesus, Fortunata Claudina",
"Family of Senra, Lu\u00eds da Costa and de Jesus, Maria",
"Family of Senra, Matias Pereira and Pav\u00e3o, B\u00e1rbara",
"Family of Senra, Miguel da Costa and Dias, Francisca J\u00falia",
"Family of Sequeira, Jo\u00e3o de Medeiros Alferes and de Melo, Maria Francisca",
"Family of Silva, Ant\u00f3nio dos Reis and Vasconcelos, Francisca Filomena",
"Family of Silva, Ant\u00f3nio Manuel Furtado and Pav\u00e3o, Maria Ang\u00e9lica",
"Family of Silva, Ant\u00f3nio Pacheco da Jr and Pacheco, Filomena Tavares",
"Family of Silva, Bruno dos Reis and Agostinha, Maria",
"Family of Silva, David dos Santos and de Sousa, Gilda Lindo",
"Family of Silva, Francisco and Silva, Diamantina",
"Family of Silva, Francisco Dda and Ricarda, Francisca",
"Family of Silva, Francisco In\u00e1cio dos Reis and Justina, Maria",
"Family of Silva, Guilherme Pacheco and Furtado, Maria da Luz Raposo",
"Family of Silva, Hor\u00e1rio Velasco Correia and Correia, Maria Teresa de Medeiros",
"Family of Silva, Jason and Escobar, Stephanie",
"Family of Silva, Jo\u00e3o dos Reis and C\u00e2ndida, Jacinta",
"Family of Silva, Jos\u00e9 Da Costa and Nunes, Isabel",
"Family of Silva, Jos\u00e9 de Medeiros and da Estrela, Ana",
"Family of Silva, Jos\u00e9 Eduardo and Mendes, Maria Gra\u00e7a",
"Family of Silva, Jos\u00e9 Maria Pacheco and Fernandes, Maria Teresa Reis",
"Family of Silva, Jos\u00e9 Raposo and Aguiar, Ant\u00f3nia de Jesus",
"Family of Silva, Jos\u00e9 Val\u00e9rio and Carreiro, Filomena",
"Family of Silva, Luis and Viveiros, Maria do Ros\u00e1rio",
"Family of Silva, Lu\u00eds de Medeiros and Moreira, Maria",
"Family of Silva, Manuel Da and Medeiros, \u00c1gueda Rodrigues de",
"Family of Silva, Manuel da Costa and da Ponte, Rosa Jacinta",
"Family of Silva, Manuel Furtado and Clara, Ana",
"Family of Silva, Stephanie",
"Family of Silva, Tom\u00e1s de Sousa and Pav\u00e3o, Vit\u00f3ria",
"Family of Sim\u00e3o, Andr\u00e9 da Costa and Vasconcelos, Ant\u00f3nia Francisca",
"Family of Sim\u00e3o, Ant\u00f3nio da Costa and J\u00falia, Maria",
"Family of Sim\u00e3o, Francisco da Costa and Rosa, Jacinta",
"Family of Sim\u00e3o, Francisco da Costa and Santo, Maria do Espirito",
"Family of Sim\u00e3o, Jo\u00e3o da Costa and Joaquina, Ana",
"Family of Sim\u00e3o, Jos\u00e9 da Costa and Ricarda, Ant\u00f3nia",
"Family of Sim\u00e3o, Manuel and Dos Anjos, Francisca",
"Family of Sim\u00e3o, Manuel da Costa and Carvalho, Maria",
"Family of Sim\u00e3o, Manuel da Costa and Joaquina, Maria",
"Family of Simas, Ant\u00f3nio Pacheco and Tavares, Luzia Ant\u00f3nia",
"Family of Simas, Domingos and Alvares, Maria",
"Family of Simas, Domingos and Columbreiro, Susana Afonso",
"Family of Simas, Manuel Franco and Furtado, Jer\u00f3nima",
"Family of Sim\u00f5es, Ant\u00f3nio and Carvalho, Maria",
"Family of Sim\u00f5es, Jo\u00e3o and Camelo, Ana Francisca",
"Family of Sim\u00f5es, Jo\u00e3o and dos Santos, Maria",
"Family of Sim\u00f5es, Jos\u00e9 da Costa and de Sousa, Benvinda",
"Family of Sim\u00f5es, Jos\u00e9 Jacinto and J\u00falia, Carlota",
"Family of Sim\u00f5es, Manuel and Barbosa, Margarida",
"Family of Sim\u00f5es, Manuel and de Oliveira, B\u00e1rbara",
"Family of Sim\u00f5es, Manuel and Dias, Catarina",
"Family of Sim\u00f5es, Manuel Ant\u00f3nio Oliveira and Miranda, Maria Helena",
"Family of Sim\u00f5es, Manuel da Costa and \u00c1lves, Maria Miquelina",
"Family of Sim\u00f5es, Sid\u00f3nio and Sim\u00f5es, Angie",
"Family of Smith, Allen and Arruda, Filomena",
"Family of Soares, Agostinho Jos\u00e9 and Joaquina, Ana",
"Family of Soares, Amaro and Carvalho, Isabel",
"Family of Soares, Ant\u00e3o and da C\u00e2mara, Maria Teresa",
"Family of Soares, Ant\u00f3nia",
"Family of Soares, Ant\u00f3nio and Cabral, Ant\u00f3nia Ferreira",
"Family of Soares, Ant\u00f3nio and Carneira, Jacinta",
"Family of Soares, Ant\u00f3nio and Carvalho, Cid\u00e1lia",
"Family of Soares, Ant\u00f3nio and de Faria, Maria de Lurdes",
"Family of Soares, Ant\u00f3nio and Rosa, Maria",
"Family of Soares, Ant\u00f3nio and Tavares, Maria do Espirito",
"Family of Soares, Ant\u00f3nio Dias and Machado, Maria",
"Family of Soares, Domingos and de Benevides, Marta",
"Family of Soares, Elias and da Estrela, Maria",
"Family of Soares, Estev\u00e3o",
"Family of Soares, Eus\u00e9bio Jos\u00e9 and de Jesus, Em\u00edlia",
"Family of Soares, Francisco and Arruda, Maria Guiomar",
"Family of Soares, Francisco and Oliveira, Maria Diamantina",
"Family of Soares, Francisco Jos\u00e9 and Rosa, M\u00f3nica",
"Family of Soares, Gon\u00e7alo and de Medeiros, Isabel",
"Family of Soares, Jacinto de Oliveira and C\u00e2ndida, Jacinta",
"Family of Soares, Joana",
"Family of Soares, Jo\u00e3o",
"Family of Soares, Jo\u00e3o and C\u00e2mara, Ana Francisca",
"Family of Soares, Jo\u00e3o and Da Conceic\u00e3o, Jos\u00e9fa",
"Family of Soares, Jo\u00e3o and de Jesus, Margarida",
"Family of Soares, Jo\u00e3o and Rosa, Francisca",
"Family of Soares, Jo\u00e3o de Oliveira and da Gl\u00f3ria, Maria",
"Family of Soares, Jo\u00e3o do Rego and de Oliveira, Ant\u00f3nia",
"Family of Soares, Jo\u00e3o do Rego and de Santiago, Ana",
"Family of Soares, Jo\u00e3o Ferreira and \u00c1lves, Francisca",
"Family of Soares, Jos\u00e9 and de Jesus, Vit\u00f3ria",
"Family of Soares, Jos\u00e9 Jr and dos Anjos, Maria",
"Family of Soares, Jos\u00e9 de Sousa and da Gl\u00f3ria, Maria Constantina",
"Family of Soares, Jos\u00e9 Elias and da Gl\u00f3ria, Maria",
"Family of Soares, Jos\u00e9 Francisco and Joaquina, Maria",
"Family of Soares, Lu\u00eds and de Arruda, Maria dos Santos",
"Family of Soares, Manuel and Cabral, Ana",
"Family of Soares, Manuel and Carvalho, Mariana da Costa",
"Family of Soares, Manuel and da Luz, Margarida",
"Family of Soares, Manuel and de Aguiar, Geraldina Vieira",
"Family of Soares, Manuel and de Medeiros, Jos\u00e9fa",
"Family of Soares, Manuel and Rego, Maria dos Anjos",
"Family of Soares, Manuel and Soares, Luzia",
"Family of Soares, Manuel Calvo and Morais, Maria da Trindade",
"Family of Soares, Manuel de Aguiar and Travassos, Maria",
"Family of Soares, Manuel Farias and De Jesus, Ana",
"Family of Soares, Manuel Ferreira and de Aguiar, Barbara",
"Family of Soares, Manuel Jos\u00e9 and dos Santos, Maria",
"Family of Soares, Manuel Raposo and da Natividade, Maria",
"Family of Soares, Maria do Espirito Santo",
"Family of Soares, Matias de Oliveira and de Viveiros, Maria",
"Family of Soares, Pedro Jos\u00e9 and Faria, Maria C\u00e2ndida",
"Family of Soares, Tom\u00e1s Ferreira and Sousa, Maria",
"Family of Soares, Vicente Do Rego and Joaquina, Antonia Maria",
"Family of Soneca, Balthezar Afonso and Ara\u00fajo, Catarina",
"Family of Soucier, Fran\u00e7ois -Regis-Xavier and Dupuis, Eug\u00e9nie",
"Family of Sousa, Agostinho and Oliveira, Francisca",
"Family of Sousa, Ant\u00f3nio Correia and Rebelo, Maria",
"Family of Sousa, Ant\u00f3nio Da Silva and Raposo, Maria da Concei\u00e7\u00e3o",
"Family of Sousa, Ant\u00f3nio De and Almeida, Barbara",
"Family of Sousa, Cristov\u00e3o Afonso Capit\u00e3o and \u00c1vares, Isabel",
"Family of Sousa, Edmundo Carvalho and Fernandes, Vit\u00f3ria Maria Viveiros",
"Family of Sousa, Elias and Furtado, Lurdes Raposo",
"Family of Sousa, Francisco De and Correia, Maria",
"Family of Sousa, Jos\u00e9 de Azevedo and de Almada, Maria Azevedo",
"Family of Sousa, Jos\u00e9 de Medeiros and de Jesus, Maria",
"Family of Sousa, Jos\u00e9 dos Reis and Da Encarna\u00e7\u00e3o, Joana Isabel",
"Family of Sousa, Jos\u00e9 Manuel Aguiar and Est\u00e1cio, Maria Olivia Cabral",
"Family of Sousa, Manuel \u00c1lvares and Cabral, Ant\u00f3nia",
"Family of Sousa, Manuel Botelho and De Jesus, Maria",
"Family of Sousa, Manuel De and Maria, Rosa",
"Family of Sousa, Manuel De and Raposo, Barbara",
"Family of Sousa, Manuel de Medeiros and Couto, Maria do Ros\u00e1rio",
"Family of Sousa, Manuel de Medeiros and Pacheco, Joana Em\u00edlia",
"Family of Sousa, Manuel de Melo and Moniz, Maria Tavares",
"Family of Sousa, Manuel de Oliveira and Manuel, B\u00e1rbara",
"Family of Sousa, Manuel de Oliveira and Vasconcelos, Maria de Ara\u00fajo",
"Family of Sousa, Manuel Pereira De and Fontes, Ant\u00f3nia Jacinta De",
"Family of Tanoeiro, Manuel Da Costa and Pavoa, Maria",
"Family of Tavares, Alexadre Pimentel and Salvador, Idalina Reis",
"Family of Tavares, Andr\u00e9 and Correia, Ant\u00f3nia do Nascimento",
"Family of Tavares, Andr\u00e9 and de Sousa, Quiteria",
"Family of Tavares, Ant\u00f3nio",
"Family of Tavares, Ant\u00f3nio and Arruda, Ant\u00f3nia Vicente",
"Family of Tavares, Ant\u00f3nio and Carvalho, Diamantina",
"Family of Tavares, Ant\u00f3nio and Cordeiro, Maria Francisca",
"Family of Tavares, Ant\u00f3nio and De Aguiar, Maria",
"Family of Tavares, Ant\u00f3nio and de Jesus, Maria",
"Family of Tavares, Ant\u00f3nio and dos Anjos, Isabel",
"Family of Tavares, Ant\u00f3nio and Francisca, Madalena",
"Family of Tavares, Ant\u00f3nio and Isabel, Maria",
"Family of Tavares, Ant\u00f3nio and Rosa, Maria",
"Family of Tavares, Ant\u00f3nio Correia and de Viveiros, Maria \u00c1lves",
"Family of Tavares, Ant\u00f3nio da Costa and Pacheco, Maria do Sacramento",
"Family of Tavares, Ant\u00f3nio da Costa and Viveiros, Vit\u00f3ria Francisca",
"Family of Tavares, Ant\u00f3nio de Medeiros and Botelho, Maria de Viveiros",
"Family of Tavares, Ant\u00f3nio de Medeiros and de Jesus, Maria",
"Family of Tavares, Ant\u00f3nio Pereira and Francisca, Maria",
"Family of Tavares, Ant\u00f3nio Pereira Junior and da Conceic\u00e3o, Maria",
"Family of Tavares, Baltazar and Cabral, Maria",
"Family of Tavares, Belchior and Tavares, Simoa",
"Family of Tavares, Daniel de Medeiros and Joaquina, Maria",
"Family of Tavares, Dimas and de Sousa, Gilda",
"Family of Tavares, Diogo Privado and de Sousa, Maria",
"Family of Tavares, Diogo Privado and Vult\u00e3o, Maria",
"Family of Tavares, Fern\u00e3o",
"Family of Tavares, Fern\u00e3o De Anes and De Morais, Isabel Gon\u00e7alves",
"Family of Tavares, Francisco and da Conceic\u00e3o, Maria",
"Family of Tavares, Francisco and de Jesus, Ana",
"Family of Tavares, Francisco and Miranda, Maria",
"Family of Tavares, Francisco and Moreira, Maria Luzia",
"Family of Tavares, Francisco and Novo, Maria de Oliveira",
"Family of Tavares, Francisco and Pedro, Maria",
"Family of Tavares, Francisco and Travassos, Maria",
"Family of Tavares, Francisco Pereira and dos Reis, Ana",
"Family of Tavares, Jo\u00e3o and Amaral, Rosa do",
"Family of Tavares, Jo\u00e3o and Arruda, Maria de Jesus",
"Family of Tavares, Jo\u00e3o and Arruda, Mariana Vicente",
"Family of Tavares, Jo\u00e3o and Augusta, Helena Francisca",
"Family of Tavares, Jo\u00e3o and de Almeida, Rosa Francisca",
"Family of Tavares, Jo\u00e3o and de Jesus, Francisca",
"Family of Tavares, Jo\u00e3o and Em\u00edlia, Helena",
"Family of Tavares, Jo\u00e3o and Gon\u00e7alves, Luzia",
"Family of Tavares, Jo\u00e3o and Pav\u00e3o, Mariana",
"Family of Tavares, Jo\u00e3o and Pav\u00e3o, Mariana",
"Family of Tavares, Jo\u00e3o Correia and Machado, Maria de Sousa",
"Family of Tavares, Jo\u00e3o da Costa and Pav\u00e3o, Marcelina",
"Family of Tavares, Jo\u00e3o da Costa and Soares, Maria",
"Family of Tavares, Jo\u00e3o Raposo and Rosa, Margarida",
"Family of Tavares, Jos\u00e9 and de Jesus, Madalena",
"Family of Tavares, Jos\u00e9 and Francisca, Vit\u00f3ria",
"Family of Tavares, Jos\u00e9 and Jacinta, Maria",
"Family of Tavares, Jos\u00e9 and Maria, Rosa",
"Family of Tavares, Jos\u00e9 and Miguel, Mariana",
"Family of Tavares, Jos\u00e9 and Rosa, Clara",
"Family of Tavares, Jos\u00e9 Correia and Albernaz, Senhorinha da Ascen\u00e7\u00e3o",
"Family of Tavares, Jos\u00e9 da Costa and Pimentel, Mariana de Jesus",
"Family of Tavares, Jos\u00e9 de Amaral and Francisca, Ant\u00f3nia",
"Family of Tavares, Jos\u00e9 Pav\u00e3o and Raposo, Leontina",
"Family of Tavares, Jos\u00e9 Pereira and Augusta, Helena",
"Family of Tavares, Jos\u00e9 Pereira and da Concei\u00e7\u00e3o, Ermelina Etelvina",
"Family of Tavares, Jos\u00e9 Pereira and Travassos, Maria da Encarna\u00e7\u00e3o",
"Family of Tavares, Jos\u00e9 Raposo and da Concei\u00e7\u00e3o, Francisca",
"Family of Tavares, Jos\u00e9 Raposo and Raposo, Maria",
"Family of Tavares, J\u00falio and de Viveiros, Margarida Rosa",
"Family of Tavares, Lu\u00eds and Aguiar, Ant\u00f3nia",
"Family of Tavares, Lu\u00eds and Almeida, Maria da Concei\u00e7\u00e3o",
"Family of Tavares, Lu\u00eds and Ernesto, Ema",
"Family of Tavares, Lu\u00eds Raposo and da Gl\u00f3ria, Maria",
"Family of Tavares, Manuel and Da Conceic\u00e3o, Maria",
"Family of Tavares, Manuel and da Encarna\u00e7\u00e3o, Silvana",
"Family of Tavares, Manuel and de Jesus, Maria",
"Family of Tavares, Manuel and de Jesus, Vit\u00f3ria",
"Family of Tavares, Manuel and de Viveiros, B\u00e1rbara",
"Family of Tavares, Manuel and Jos\u00e9, Maria de S\u00e3o",
"Family of Tavares, Manuel and Raposo, Barbara",
"Family of Tavares, Manuel and Rebelo, Concei\u00e7\u00e3o",
"Family of Tavares, Manuel and Rosa, Ana",
"Family of Tavares, Manuel and Xavier, Catarina",
"Family of Tavares, Manuel * and Rosa, Madalena",
"Family of Tavares, Manuel * and Santo, Sebastiana do Espirito",
"Family of Tavares, Manuel Arruda and Hutchinson, Loretta Catherine",
"Family of Tavares, Manuel Carvalho and Furtado, Lib\u00e9lia",
"Family of Tavares, Manuel da Costa and Faria, Senhorinha de Sousa",
"Family of Tavares, Manuel de Medeiros and da Encarna\u00e7\u00e3o, Vit\u00f3ria",
"Family of Tavares, Manuel de Medeiros and de Viveiros, Vit\u00f3ria",
"Family of Tavares, Manuel Pereira and Carvalho, Maria Rosalina",
"Family of Tavares, Manuel Pereira and Cordeiro, Miquelina Zeferino dos Reis",
"Family of Tavares, Manuel Pereira and da Gl\u00f3ria, Alexandrina",
"Family of Tavares, Manuel Pereira and Vic\u00eancia, Ant\u00f3nia",
"Family of Tavares, Manuel Raposo and Carvalho, Guilhermina da Conceic\u00e3o",
"Family of Tavares, Manuel Raposo and de Jesus, Margarida",
"Family of Tavares, Manuel Raposo and dos Reis, Violante Fernandes",
"Family of Tavares, Manuel Raposo and J\u00falia, Maria",
"Family of Tavares, Manuel Raposo and Santo, Ana do Esp\u00edrito",
"Family of Tavares, Messias and Tavares, Olga",
"Family of Tavares, Miguel and De Sousa, Maria",
"Family of Tavares, Nat\u00e1lia and Lindo, Lu\u00eds Cabral",
"Family of Tavares, Ricardo Pereira and de Jesus, Ricarda",
"Family of Tavares, Rui and Afonso, Lianor",
"Family of Tavares, Silvino and Vieira, Maria do Espirito Santo",
"Family of Tavares, Urbano Pereira and Angelina, Maria",
"Family of Tavares, Vitorino and de Jesus, Maria",
"Family of Teixeira, Ant\u00f3nio \u00c1lvares and \u00c1lvares, Maria",
"Family of Teixeira, Ant\u00f3nio Dias and de Jesus, Teresa",
"Family of Teixeira, Diogo and Gaspar, Francisca",
"Family of Teixeira, Jo\u00e3o * and de Benevides, Isabel",
"Family of Teixeira, Jos\u00e9 and Furtado, Maria",
"Family of Teixeira, Jos\u00e9 and Gon\u00e7alves, Maria da Costa",
"Family of Teixeira, Jos\u00e9 Francisco and J\u00falia, Mariana",
"Family of Teixeira, Manuel and Martins, Ant\u00f3nia",
"Family of Teixeira, Manuel and Pacheco, Ana Jacinta",
"Family of Teixeira, Manuel \u00c1lvares and Fernandes, Clara",
"Family of Teixeira, Manuel \u00c1lvares and Lima, Francisca de Sousa",
"Family of Teixeira, Manuel De Sousa and Nunes, Ana",
"Family of Teixeira, Manuel Fernandes and Resendes, Maria",
"Family of Terra, Helder dos Santos Silva and Carvalho, Maria de Lurdes Pimentel",
"Family of Terreira, Ant\u00f3nio Da Luz and De Jesus, Emiliana Do Cora\u00e7\u00e3o",
"Family of Teve, Br\u00e1s and Oliveira, Maria",
"Family of Teve, Manuel Da Costa and De Sousa, Barbara",
"Family of Teves, Ant\u00f3nio and de Benevides, Guiomar",
"Family of Teves, Armando and Isabel, Mariana",
"Family of Teves, Dinis and de Farias, Maria Pav\u00e3o",
"Family of Teves, Hermano Miguel and Freitas, Maria Guilhermina Est\u00e1cio",
"Family of Theodore, Jos\u00e9 and Augusta, Florinda",
"Family of Tom\u00e1sia, Jacinta",
"Family of Tom\u00e9, Antonio and Faria, Maria",
"Family of Tom\u00e9, Jos\u00e9 and Anjos, Maria do",
"Family of Torres, Jorge and Costa, Clotilde",
"Family of Toste, Agostinho Gon\u00e7alves Pereira and da Cunha, B\u00e1rbara Pereira",
"Family of Travasos, Manuel and Nunes, M\u00f3nica",
"Family of Travassos, Agostinho and De Jesus, Margarida",
"Family of Travassos, Amaro da Costa and Furtado, \u00c1gueda Rodrigues",
"Family of Travassos, Amaro da Costa and Rodovalho, Maria Cabeceiras",
"Family of Travassos, Ant\u00f3nio and de Jesus, Vit\u00f3ria",
"Family of Travassos, Ant\u00f3nio and Francisca, Ana",
"Family of Travassos, Ant\u00f3nio and Joaquina, Maria",
"Family of Travassos, Ant\u00f3nio and Pimentel, Ana",
"Family of Travassos, Ant\u00f3nio de Sousa and de Sousa, Barbara",
"Family of Travassos, Ant\u00f3nio Viveiros and Vasconcelos, Maria Ara\u00fajo",
"Family of Travassos, Estev\u00e3o Cabral and Afonso, Violante Gon\u00e7alves",
"Family of Travassos, Francisco and de Viveiros, Ana",
"Family of Travassos, Francisco da Costa and de Sousa, Ana",
"Family of Travassos, Francisco Pimentel and da Encarna\u00e7\u00e3o, Jacinta",
"Family of Travassos, George da Costa and da Silva, Beatriz",
"Family of Travassos, Jacinto and Botelho, Policarpa Augusta",
"Family of Travassos, Jo\u00e3o and da Estrela, Maria",
"Family of Travassos, Jo\u00e3o and de Jesus, Margarida",
"Family of Travassos, Jo\u00e3o de Sousa and de Benevides, Maria",
"Family of Travassos, Jos\u00e9 * and Viveiros, Teresa",
"Family of Travassos, Jos\u00e9 Agostinho and Rego, Alice do",
"Family of Travassos, Jos\u00e9 de Viveiros and Arruda, Const\u00e2ncia",
"Family of Travassos, Jos\u00e9 Martins and Aguiar, Eug\u00eania Rosa",
"Family of Travassos, Manuel and Amaral, Maria do Espirito Santo",
"Family of Travassos, Manuel and da Costa, Maria J\u00falia",
"Family of Travassos, Manuel and Joaquina, Maria",
"Family of Travassos, Manuel and Maria, Ant\u00f3nia",
"Family of Travassos, Manuel \u00c1lvares and Cabral, Francisca",
"Family of Travassos, Manuel De Sousa and Miguel, Teresa De Sao",
"Family of Travassos, Manuel de Viveiros and Sousa, \u00c1gueda de Jesus",
"Family of Travassos, Manuel Dias and De Medeiros, Barbara",
"Family of Travassos, Manuel do Couto and de Melo, Maria",
"Family of Travassos, Manuel do Rego Martins and de Jesus, In\u00eas",
"Family of Travassos, Nicolau da Costa and Gon\u00e7alves, Barbara",
"Family of Travassos, Rui Velho and de Aguiar, Ana",
"Family of Travassos, Rui Velho and de Teves, Guiomar",
"Family of Unknown",
"Family of Unknown",
"Family of Unknown and Almeida, Ant\u00f3nia",
"Family of Unknown and da Costa, Maria Carolina",
"Family of Unknown and De Sousa, Joana",
"Family of Unknown and de Viveiros, Maria",
"Family of Unknown and de Viveiros, Maria Guiomar",
"Family of Unknown and Divino, Jacinta do Amor",
"Family of Unknown and Est\u00e1cio, Helena da Concei\u00e7\u00e3o",
"Family of Unknown and Fernandes, Senhorinha",
"Family of Unknown and Francisca, Rosa",
"Family of Unknown and Guiomar, Ant\u00f3nia de Jesus",
"Family of Unknown and Machado, Francisca",
"Family of Unknown and Martinho, Maria",
"Family of Unknown and Oliveira, Maria",
"Family of Unknown and Pav\u00e3o, Ana",
"Family of Unknown and Pav\u00e3o, Francisca",
"Family of Unknown and Raposo, Rosa Augusta da Concei\u00e7\u00e3o",
"Family of Unknown and Unknown",
"Family of Unknown, Father",
"Family of Unknown, Father and Unknown, Motther",
"Family of Unknown, Parents",
"Family of Unknown, Parents",
"Family of Unknown, Parents",
"Family of Unknwon and Oliveira, Ana de Santo Andr\u00e9",
"Family of Unkonwn",
"Family of Urbain, Joseph and Ranger, Ang\u00e9lique",
"Family of Vaconcelos, Ant\u00f3nio Francisco Capeto and Joaquina, Maria",
"Family of Vaconcelos, Francisco Capeto and Cordeiro, Maria Isabel",
"Family of Vaconcelos, Joaquim Capeto and Carmo, Maria do",
"Family of Vaconcelos, Lu\u00eds Capeto and Aguiar, Maria dos Anjos Sousa",
"Family of Valentim, Jo\u00e3o Aguiar and de Jesus, Maria",
"Family of Valentim, Jos\u00e9 Aguiar and da Conceic\u00e3o, Rosa",
"Family of Valentim, Jos\u00e9 Aguiar and Tavares, Maria dos Anjos",
"Family of Valentim, Jos\u00e9 Humberto Tavares and de Sousa, Dulce",
"Family of Valentim, Manuel Aguiar and da Estrela, Maria",
"Family of Valentino, Francisco de Aguiar and de Jesus, Maria",
"Family of Valentino, Manuel de Aguiar and Martins, Ant\u00f3nia Isabel",
"Family of Val\u00e9rio, Jo\u00e3o Cabral and da Estrela, Mariana",
"Family of Val\u00e9rio, Jos\u00e9 In\u00e1cio and Ferreira, Ant\u00f3nia",
"Family of Vascocelos, Jos\u00e9 Francisco Capeto and Machado, Maria Jos\u00e9",
"Family of Vascocelos, Salvador de Oliveira and Pereira, Barbara",
"Family of Vasconcelos, Afonso Oliveira and Lopes, Solanda",
"Family of Vasconcelos, Agostinho de Viveiros and Leonarda, Ana",
"Family of Vasconcelos, Amador and Ara\u00fajo, Beatriz Pessoa",
"Family of Vasconcelos, Ant\u00f3nio da Costa and Francisca, B\u00e1rbara",
"Family of Vasconcelos, Ant\u00f3nio de Sousa cap. and de Melo, Vit\u00f3ria Francisca",
"Family of Vasconcelos, Ant\u00f3nio de Viveiros and de Benevides, Margarida \u00c1lvares",
"Family of Vasconcelos, Augusto and Botelho, Maria Fernanda Lopes",
"Family of Vasconcelos, Bartolomeu Amaral and Carneiros, Francisca",
"Family of Vasconcelos, Diogo De Oliveira and Esteves, Maria",
"Family of Vasconcelos, Diogo de Viveiros e and Rodovalho, Maria",
"Family of Vasconcelos, Francisco and Rosa, Luzia",
"Family of Vasconcelos, Francisco de Oliveira and de Viveiros, Clara",
"Family of Vasconcelos, Jaime Botelho and Senra, Violante da Gl\u00f3ria da Costa",
"Family of Vasconcelos, Jo\u00e3o da Costa and da Luz, Maria",
"Family of Vasconcelos, Jo\u00e3o da Costa and de Jesus, Carolina",
"Family of Vasconcelos, Jo\u00e3o D\u00e2masio and de Medeiros, Virgina",
"Family of Vasconcelos, Jo\u00e3o de Viveiros and de Viveiros, B\u00e1rbara",
"Family of Vasconcelos, Jo\u00e3o De Viveiros and Estrela, Maria Da",
"Family of Vasconcelos, Joaquim Ant\u00f3nio and Isabel, Maria",
"Family of Vasconcelos, Jos\u00e9 da Costa and da Conceic\u00e3o, Justina",
"Family of Vasconcelos, Jos\u00e9 da Costa and da Concei\u00e7\u00e3o, Vit\u00f3ria",
"Family of Vasconcelos, Jos\u00e9 da Costa and da Costa, B\u00e1rbara",
"Family of Vasconcelos, Jos\u00e9 da Costa and Francisca, Ant\u00f3nia",
"Family of Vasconcelos, Jos\u00e9 da Costa and Rodrigues, Margarida Pedro",
"Family of Vasconcelos, Jos\u00e9 de Melo and Santo, Quit\u00e9ria do Espirito",
"Family of Vasconcelos, Jos\u00e9 de Viveiros and de Jesus, Vit\u00f3ria",
"Family of Vasconcelos, Jos\u00e9 Fernandes and da Costa, B\u00e1rbara",
"Family of Vasconcelos, Jos\u00e9 Fernandes and Francisca",
"Family of Vasconcelos, Jos\u00e9 Maria and Leonilde, Maria",
"Family of Vasconcelos, Luis Ant\u00f3nio and Melo, Maria Rosa dos Anjos",
"Family of Vasconcelos, Luis Aguiar Capeto and Arruda, Maria do Carmo",
"Family of Vasconcelos, Lu\u00eds Dias and Fernandes, Deolinda Rem\u00edgio",
"Family of Vasconcelos, Luis Jos\u00e9 de and Cabral, Maria Isabel",
"Family of Vasconcelos, Manuel \u00c1lvares and Martins, Ana",
"Family of Vasconcelos, Manuel \u00c1lvares Capit\u00e3o and de Amaral, Ana",
"Family of Vasconcelos, Manuel \u00c1lvares Capit\u00e3o and Fragoso, Maria",
"Family of Vasconcelos, Manuel Antonio and Miranda, Margarida Vasconcelos",
"Family of Vasconcelos, Manuel Ant\u00f3nio and Carlos, Maria da Concei\u00e7\u00e3o",
"Family of Vasconcelos, Manuel da Costa and Camela, Maria Pav\u00e3o",
"Family of Vasconcelos, Manuel da Costa and da Conceic\u00e3o, Ana",
"Family of Vasconcelos, Manuel da Costa and Jos\u00e9, Maria",
"Family of Vasconcelos, Manuel de Oliveira and Cabral, B\u00e1rbara",
"Family of Vasconcelos, Manuel de Oliveira and de Sousa, Beatriz",
"Family of Vasconcelos, Manuel de Sousa and Ferreira, Maria Carvalho",
"Family of Vasconcelos, Manuel de Viveiros and de Benevides, Isabel Faria",
"Family of Vasconcelos, Manuel De Viveiros and Rego, Francisca De Medeiros Do",
"Family of Vasconcelos, Manuel de Viveiros Rego and Pacheco, Mariana Augusta",
"Family of Vasconcelos, Manuel Oliveira and Lopes, Maria Rodrigues",
"Family of Vasconcelos, Manuel Pav\u00e3o de and de Viveiros, Maria",
"Family of Vasconcelos, Manuel Raposo and Leite, Margarida Furtado",
"Family of Vasconcelos, Martim De Oliveira and Afonso, Catarina",
"Family of Vasconcelos, Paulo de Sousa and Revoredo, Maria",
"Family of Vasconcelos, Pedro De Oliveira and Ara\u00fajo, Catarina",
"Family of Vasconcelos, Rui Oliveira",
"Family of Vasconcelos, Sebasti\u00e3o da Costa and de Arruda, Maria",
"Family of Vasconcelos, Sebasti\u00e3o da Costa and Pav\u00e3o, Barbara",
"Family of Vasconcelos, Sebasti\u00e3o de Oliveira and de Sousa, Maria Benevides",
"Family of Vasques, Greg\u00f3rio and de Jesus, Ana Clemantina",
"Family of Vaz, Ant\u00f3nio and Aguiar, Maria",
"Family of Vaz, Gil and Anes, Maria",
"Family of Vaz, Manuel",
"Family of Vaz, Manuel and de Medeiros, B\u00e1rbara",
"Family of Velho, Afonso and Esteves, F",
"Family of Velho, \u00c1lvaro",
"Family of Velho, Andr\u00e9 de Sousa and Ara\u00fajo, Maria da Cruz",
"Family of Velho, Ant\u00f3nio and Santo, Maria do Espirito",
"Family of Velho, Ant\u00f3nio Cabral and de Viveiros, Maria",
"Family of Velho, Bartolomeu Travassos and Couto, \u00darsula do",
"Family of Velho, Fern\u00e3o and Cabral, D. Maria \u00c1vares",
"Family of Velho, Francisco and de Viveiros, Ana",
"Family of Velho, Francisco and Sousa, Ant\u00f3nia",
"Family of Velho, Francisco de Sousa and Arruda, In\u00e1cia Joaquina de",
"Family of Velho, Gon\u00e7alo and Afonso, Margarida",
"Family of Velho, Gon\u00e7alo O Contador and De Urr\u00f3, D.Margarida Anes",
"Family of Velho, Jo\u00e3o de Viveiros and de Viveiros, Isabel Ant\u00f3nia",
"Family of Velho, Jo\u00e3o Pires and Correia, Martinha Soares D.",
"Family of Velho, Lopo",
"Family of Velho, L\u00facio de Medeiros and de Jesus, Maria",
"Family of Velho, Manuel and de Viveiros, Ana",
"Family of Velho, Manuel de Sousa and da Estrela, Escolastica",
"Family of Velho, Manuel de Sousa and Tavares, Rosa Francisca",
"Family of Velho, Melchior and Rodrigues, Susana",
"Family of Vernandes, Gil and Vicente, Joana",
"Family of Vernandes, Gil and Vicente, Joana",
"Family of Vicente, Francisco and Aguiar, Maria da Conceic\u00e3o",
"Family of Vicente, Manuel do Rego and Ponte, Ana Carolina da",
"Family of Vicente, Savador and Lopes, Isabel",
"Family of Vidal, Francisco Teixeira and De Fontes, Maria",
"Family of Vidal, Jo\u00e3o da Ponte and Pinheiro, Ana",
"Family of Vieira, Ant\u00f3nio and Pereira, Maria",
"Family of Vieira, Jos\u00e9 and Rosa, Catarina",
"Family of Vieira, Jos\u00e9 Ant\u00f3nio and de Sousa, Od\u00e9lcia",
"Family of Vieira, Manuel and Correia, Angela",
"Family of Vieira, Manuel and da Trindade, Maria",
"Family of Vieira, Manuel and De Teves, Margarida",
"Family of Vieira, Manuel and Fagundes, Jos\u00e9fa",
"Family of Vieira, Manuel and Ganhadeiro, Maria da Ponte",
"Family of Vieira, Manuel and Rodrigues, Barbara",
"Family of Vieira, Manuel De Sousa and Da Concei\u00e7\u00e3o, Ant\u00f3nia",
"Family of Vieira, Manuel Jos\u00e9 and Jacinta, Maria",
"Family of Vieira, Manuel Pacheco and De Jesus, Ricarda",
"Family of Vieira, Maur\u00edcio Jos\u00e9 and de Jesus, Maria",
"Family of Vieira, Pedro Martins and Carreiro, Luzia",
"Family of Vieira, Pedro Rego and Rodrigues, Maria",
"Family of Vitorino, Manuel and de Azevedo, Maria Barbara Jos\u00e9fa",
"Family of Viveiros, Andr\u00e9 de and Costa, Marcelina",
"Family of Viveiros, Ant\u00e9ro Carlos and Lucier, Robin J.",
"Family of Viveiros, Ant\u00e9ro Guiomar and Pav\u00e3o, Z\u00e9lia Maria",
"Family of Viveiros, Antonio and Moreira, Hilda",
"Family of Viveiros, Ant\u00f3nio and Vasconcelos, Quiteria de Medeiros",
"Family of Viveiros, Ant\u00f3nio De and Quaresma, Francisca Rosa",
"Family of Viveiros, Ant\u00f3nio De Medeiros and Estrela, Maria Da Costa",
"Family of Viveiros, Ant\u00f3nio Eduardo Sousa and Carvalho, Maria Helena",
"Family of Viveiros, Ant\u00f3nio Guiomar and da Costa, Mariana Augusta",
"Family of Viveiros, Ant\u00f3nio Guiomar and da Luz, Maria",
"Family of Viveiros, Ant\u00f3nio Machado and Sofia, Maria",
"Family of Viveiros, Ant\u00f3nio Manuel Camara and Baillie, \u200eSandra",
"Family of Viveiros, Ant\u00f3nio Manuel Camara and Jarvis, Judy Bernice",
"Family of Viveiros, Ant\u00f3nio Vitorino and Costa, Rosa da Concei\u00e7\u00e3o",
"Family of Viveiros, Augusto \u00c1lves and Ferreira, Maria Tavares",
"Family of Viveiros, Brian Edward and Lewis, Ashly",
"Family of Viveiros, Carlos Alberto Diogo and Baker, Ginette",
"Family of Viveiros, Carlos Alberto Diogo and Hupe, Line",
"Family of Viveiros, Daniel Kirk Russell and Walsh, Dayna",
"Family of Viveiros, Diogo and Carvalha, Maria",
"Family of Viveiros, Eduardo and Vaz, Marilia",
"Family of Viveiros, Eduardo Pacheco and Raposo, Deolinda",
"Family of Viveiros, Francisco Pacheco and Viveiros, Maria da Concei\u00e7\u00e3o",
"Family of Viveiros, Gaspar de and Benevides, Maria",
"Family of Viveiros, Geraldo Ant\u00e9ro and C\u00e2mara, Maria da Concei\u00e7\u00e3o",
"Family of Viveiros, Gilberto Sousa and Fonseca, Maria Silvina Raposo",
"Family of Viveiros, Guilherme and Diogo, Irene Rodrigues",
"Family of Viveiros, Guilherme and Viveiros, Gilda Costa",
"Family of Viveiros, Hermano Correia and Viveiros, Maria Teresa",
"Family of Viveiros, J\u00e1come and Botelha, Francisca",
"Family of Viveiros, Jo\u00e3o and de Benevides, Maria",
"Family of Viveiros, Jo\u00e3o and Oliveira, Rosa",
"Family of Viveiros, Jo\u00e3o de Sousa and Pereira, Maria da Concei\u00e7\u00e3o",
"Family of Viveiros, Jo\u00e3o Pacheco and Pereira, Maria Jos\u00e9",
"Family of Viveiros, Jo\u00e3o Raposo and Arruda, Maria de Fatima",
"Family of Viveiros, Jos\u00e9 and da Conceic\u00e3o, Barbara",
"Family of Viveiros, Jos\u00e9 de Medeiros and Machado, Maria de Fatima Gon\u00e7alves",
"Family of Viveiros, Jos\u00e9 Francisco de and Couto, Ana Margarida",
"Family of Viveiros, Jos\u00e9 Guiomar and Guiomar, \u00darsula",
"Family of Viveiros, Jos\u00e9 Guiomar and Sousa, Maria da Gl\u00f3ria Matias",
"Family of Viveiros, Jos\u00e9 Manuel Arruda and De Medeiros, Ana Maria",
"Family of Viveiros, Jos\u00e9 Maria de Sousa and Oliveira, Maria de Lurdes Fernandes",
"Family of Viveiros, Jos\u00e9 Pacheco and Tavares, Maria Rebelo",
"Family of Viveiros, Jos\u00e9 Pereira and Jo\u00e3o, Francisca De S\u00e3o",
"Family of Viveiros, Manuel de Arruda and de Viveiros, Francisca Joaquina",
"Family of Viveiros, Manuel Guiomar and C\u00e2mara, Catarina Sousa Carlos",
"Family of Viveiros, Manuel Guiomar and Viveiros, Gl\u00f3ria",
"Family of Viveiros, Manuel Pacheco and Arruda, Alice Martins",
"Family of Viveiros, Manuel Pav\u00e3o and Costa, Alzira Miguel",
"Family of Viveiros, Manuel Vitorino and Moreira, Maria De Lurdes",
"Family of Viveiros, Mara and Rodovalho, Ant\u00f3nio da Costa",
"Family of Viveiros, Maria da Concei\u00e7\u00e3o and Soares, Jos\u00e9",
"Family of Viveiros, Mario Jorge Diogo and Rousseau, Manon",
"Family of Viveiros, Vitorino Raposo de and Jesus, Maria de",
"Family of Vult\u00e3o, Ant\u00f3nio da Costa and Cabral, Joana",
"Family of Vult\u00e3o, Ant\u00f3nio da Costa and Pacheco, Joana da Concei\u00e7\u00e3o",
"Family of Vult\u00e3o, Ant\u00f3nio de Viveiros and Aguiar, Maria das Neves",
"Family of Vult\u00e3o, Ant\u00f3nio de Viveiros and Neves, Maria das",
"Family of Vult\u00e3o, Ant\u00f3nio de Viveiros and Tom\u00e1sia, Maria",
"Family of Vult\u00e3o, Diogo Fernandes and Medeiros, Luzia",
"Family of Vult\u00e3o, Jacinto da Costa and Rodrigues, Anast\u00e1cia",
"Family of Vult\u00e3o, Jo\u00e3o de Viveiros and Raposo, Serafina de Jesus",
"Family of Vult\u00e3o, Jos\u00e9 and De Benevides, Maria",
"Family of Vult\u00e3o, Jos\u00e9 da Costa and Carvalha, Maria",
"Family of Vult\u00e3o, Jos\u00e9 da Costa and de Jesus, Joana",
"Family of Vult\u00e3o, Jos\u00e9 da Costa and de Viveiros, Barbara",
"Family of Vult\u00e3o, Manuel and de Aguiar, Vit\u00f3ria",
"Family of Vult\u00e3o, Manuel and Medeiros, Ana",
"Family of Vult\u00e3o, Manuel \u00c1lves and Pav\u00e3o, Catarina",
"Family of Vult\u00e3o, Manuel da Costa and da Costa, Ana",
"Family of Vult\u00e3o, Manuel da Costa and de Benevides, Joana",
"Family of Vult\u00e3o, Manuel da Costa and De Medeiros, Margarida",
"Family of Vult\u00e3o, Manuel da Costa and de Vasconcelos, Gertrudes",
"Family of Vult\u00e3o, Manuel da Costa and Raposo, Ana",
"Family of Vult\u00e3o, Manuel de Aguiar and dos Anjos, Barbara",
"Family of Vult\u00e3o, Manuel de Sousa and Botelho, Ana",
"Family of Vult\u00e3o, Manuel Fernandes and da Costa, B\u00e1rbara",
"Family of Vult\u00e3o, Manuel Gon\u00e7alves and Carneiro, Margarida",
"Family of Vult\u00e3o, Manuel Rodrigues and de Oliveira, Catarina",
"Family of Vult\u00e3o, Mateus and Ferreira, Maria",
"Family of Vult\u00e3o, Pedro De Sousa and Soares, Maria",
"Family of Vult\u00e3o, Sim\u00e3o Dias and de Vasconcelos, Maria",
"Family of Vult\u00e3o, Sim\u00e3o Fernandes and Viveiros, Beatriz"
]
Dwr.ScriptLoaded('dwr_db_F_name_1.js');
